version: 2
jobs:
  build:
    working_directory: ~/elastiquartz
    docker:
      - image: java:8u111-jdk
    steps:
      - checkout
      - run:
          name: test
          command: ./gradlew test
      - run:
          name: build 
          command: ./gradlew build 
      - persist_to_workspace:
          root: .
          paths:
            - .

  release:
    working_directory: ~/elastiquartz
    docker:
      - image: java:8u111-jdk
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 17.06.0-ce
          reusable: true
      - run:
          name: install Docker clinet
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: docker build
          command: docker build -t stormcat24/elastiquartz:latest .
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: release latest
          command: docker push stormcat24/elastiquartz:latest

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build 
          filters:
            branches:
              only: master
